version: "3.7"
services:
  api:
    stdin_open: true
    tty: true
    build: .
    container_name: api
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle install && rails s -b '0.0.0.0' -p 3000"
    volumes:
      - .:/api
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: pass
    ports:
      - 3306:3306
    # volumes:
    #   - mysql_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8888:80
    depends_on:
      - db
    links:
      - db:db
    environment:
      PMA_HOST: "db"
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: pass
# volumes:
# mysql_data:
